from pymongo.database import Database


def ensure_indexes(db: Database) -> None:
    db.users.create_index("id", unique=True)
    db.users.create_index("phone_number", unique=True)
    db.users.create_index("yandex_id", unique=True, sparse=True)
    db.users.create_index("public_handle", unique=True, sparse=True)
    db.users.create_index([("discovery_enabled", 1), ("search_name", 1)])
    db.friends.create_index("id", unique=True)
    db.friends.create_index("pair_key", unique=True)
    db.friends.create_index([("requester_id", 1), ("status", 1)])
    db.friends.create_index([("addressee_id", 1), ("status", 1)])
    db.user_contacts.create_index("id", unique=True)
    db.user_contacts.create_index([("owner_user_id", 1), ("phone_hash", 1)], unique=True)
    db.user_contacts.create_index([("owner_user_id", 1), ("display_name", 1)])
    db.user_contacts.create_index([("owner_user_id", 1), ("matched_user_id", 1)])
    db.refresh_tokens.create_index("token_hash", unique=True)
    db.refresh_tokens.create_index("expires_at", expireAfterSeconds=0)
    db.events.create_index("id", unique=True)
    db.event_memberships.create_index("id", unique=True)
    db.event_memberships.create_index([("event_id", 1), ("user_id", 1)], unique=True)
    db.event_memberships.create_index([("user_id", 1), ("status", 1)])
    db.event_invites.create_index("id", unique=True)
    db.event_invites.create_index("token", unique=True)
    db.event_invites.create_index([("event_id", 1), ("status", 1)])
    db.invite_decisions.create_index("id", unique=True)
    db.invite_decisions.create_index(
        [("invite_type", 1), ("invite_id", 1), ("user_id", 1)], unique=True
    )
    db.invite_decisions.create_index([("event_id", 1), ("user_id", 1)])
    db.receipts.create_index("id", unique=True)
    db.receipts.create_index([("event_id", 1), ("created_at", -1)])
    db.receipts.create_index([("event_id", 1), ("status", 1)])
    db.receipt_share_reviews.create_index("id", unique=True)
    db.receipt_share_reviews.create_index([("receipt_id", 1), ("user_id", 1)], unique=True)
    db.receipt_share_reviews.create_index([("event_id", 1), ("status", 1)])
    db.receipt_share_reviews.create_index([("user_id", 1), ("status", 1)])
    db.receipt_allocation_sessions.create_index("id", unique=True)
    db.receipt_allocation_sessions.create_index([("receipt_id", 1), ("status", 1)])
    db.receipt_item_claims.create_index("id", unique=True)
    db.receipt_item_claims.create_index([("session_id", 1), ("receipt_item_id", 1)])
    db.receipt_item_claims.create_index([("session_id", 1), ("user_id", 1)])
    db.payments.create_index("id", unique=True)
    db.payments.create_index([("event_id", 1), ("created_at", -1)])
    db.payment_requests.create_index("id", unique=True)
    db.payment_requests.create_index([("event_id", 1), ("created_at", -1)])
    db.payment_requests.create_index([("debtor_id", 1), ("status", 1)])
    db.payment_requests.create_index([("creditor_id", 1), ("status", 1)])
    db.settlement_plans.create_index("id", unique=True)
    db.settlement_plans.create_index([("event_id", 1), ("created_at", -1)])
    db.settlement_plans.create_index("active_key", unique=True, sparse=True)
    db.disputes.create_index("id", unique=True)
    db.disputes.create_index([("event_id", 1), ("created_at", -1)])
    db.disputes.create_index([("resource_type", 1), ("resource_id", 1)])
    db.client_feedback_reports.create_index("id", unique=True)
    db.client_feedback_reports.create_index([("status", 1), ("created_at", -1)])
    db.client_feedback_reports.create_index([("actor_user_id", 1), ("created_at", -1)])
    db.client_feedback_reports.create_index([("request_id", 1)])
    db.client_feedback_reports.create_index([("client_trace_id", 1)])
    db.idempotency_keys.create_index([("actor_user_id", 1), ("scope", 1), ("key", 1)], unique=True)
    db.idempotency_keys.create_index("created_at", expireAfterSeconds=60 * 60 * 24)
