from pymongo.database import Database


def ensure_indexes(db: Database) -> None:
    db.users.create_index("id", unique=True)
    db.users.create_index("phone_number", unique=True)
    db.users.create_index("yandex_id", unique=True, sparse=True)
    db.users.create_index("public_handle", unique=True, sparse=True)
    db.users.create_index([("discovery_enabled", 1), ("search_name", 1)])
    db.friends.create_index("id", unique=True)
    db.friends.create_index("pair_key", unique=True)
    db.friends.create_index([("requester_id", 1), ("status", 1)])
    db.friends.create_index([("addressee_id", 1), ("status", 1)])
    db.refresh_tokens.create_index("token_hash", unique=True)
    db.refresh_tokens.create_index("expires_at", expireAfterSeconds=0)
    db.events.create_index("id", unique=True)
    db.event_memberships.create_index("id", unique=True)
    db.event_memberships.create_index([("event_id", 1), ("user_id", 1)], unique=True)
    db.event_memberships.create_index([("user_id", 1), ("status", 1)])
    db.event_invites.create_index("id", unique=True)
    db.event_invites.create_index("token", unique=True)
    db.event_invites.create_index([("event_id", 1), ("status", 1)])
    db.nearby_invite_codes.create_index("id", unique=True)
    db.nearby_invite_codes.create_index([("code", 1), ("status", 1)])
    db.nearby_invite_codes.create_index([("event_id", 1), ("status", 1)])
    db.receipts.create_index("id", unique=True)
    db.receipts.create_index([("event_id", 1), ("created_at", -1)])
    db.payments.create_index("id", unique=True)
    db.payments.create_index([("event_id", 1), ("created_at", -1)])
    db.payment_requests.create_index("id", unique=True)
    db.payment_requests.create_index([("event_id", 1), ("created_at", -1)])
    db.payment_requests.create_index([("debtor_id", 1), ("status", 1)])
    db.payment_requests.create_index([("creditor_id", 1), ("status", 1)])
    db.idempotency_keys.create_index(
        [("actor_user_id", 1), ("scope", 1), ("key", 1)], unique=True
    )
    db.idempotency_keys.create_index("created_at", expireAfterSeconds=60 * 60 * 24)
