"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Bot, CalendarCheck, Check, ExternalLink, Image as ImageIcon, PencilLine, ReceiptText, Send } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { money, SplitikAttachment, SplitikDraft } from "@/lib/splitapp-api";
import { cn } from "@/lib/utils";

export type ChatMessage = {
  id: string;
  from: "user" | "splitik";
  text: string;
  delivery?: "failed";
  retryMessage?: string;
  idempotencyKey?: string;
  drafts?: SplitikDraft[];
  questions?: Array<{ id: string; text: string }>;
};

function useVisualViewportHeight(enabled: boolean) {
  const [height, setHeight] = useState<number | null>(null);
  useEffect(() => {
    if (!enabled || !window.visualViewport) return;
    const viewport = window.visualViewport;
    const updateHeight = () => setHeight(Math.round(viewport.height));
    updateHeight();
    viewport.addEventListener("resize", updateHeight);
    viewport.addEventListener("scroll", updateHeight);
    return () => { viewport.removeEventListener("resize", updateHeight); viewport.removeEventListener("scroll", updateHeight); };
  }, [enabled]);
  return height;
}

export function SplitikScreen({ messages, draft, onDraft, onSend, isSending, attachments, isAttachmentUploading, onAttachReceipt, onConfirmDraft, onCreateEventManually }: {
  messages: ChatMessage[]; draft: string; onDraft: (value: string) => void;
  onSend: (retryMessage?: string, retryUserMessageId?: string, retryIdempotencyKey?: string) => void;
  isSending: boolean; attachments: SplitikAttachment[]; isAttachmentUploading: boolean;
  onAttachReceipt: (file: File) => void; onConfirmDraft: (draftId: string) => void; onCreateEventManually: (message: string) => void;
}) {
  const messageInputRef = useRef<HTMLTextAreaElement | null>(null);
  const messageEndRef = useRef<HTMLDivElement | null>(null);
  const [activeDraft, setActiveDraft] = useState<SplitikDraft | null>(null);
  const [isNearLatestMessage, setIsNearLatestMessage] = useState(true);
  const visualViewportHeight = useVisualViewportHeight(true);
  const scrollToLatestMessage = useCallback((force = false) => { if (force || isNearLatestMessage) messageEndRef.current?.scrollIntoView({ block: "end", behavior: "auto" }); }, [isNearLatestMessage]);
  useEffect(() => { scrollToLatestMessage(); }, [messages.length, scrollToLatestMessage, visualViewportHeight]);
  const updateDraft = (value: string) => { onDraft(value); window.requestAnimationFrame(() => { const input = messageInputRef.current; if (!input) return; input.style.height = "auto"; input.style.height = `${Math.min(input.scrollHeight, 132)}px`; }); };
  const applyDraftPrompt = (value: string) => { updateDraft(value); window.requestAnimationFrame(() => { messageInputRef.current?.focus(); scrollToLatestMessage(true); }); };
  return <div data-testid="splitik-chat-screen" style={visualViewportHeight ? { height: `${visualViewportHeight}px` } : undefined} className="flex min-h-0 bg-[#1f3d8f] text-white"><section className="mx-auto flex min-h-0 w-[var(--content-width)] flex-1 flex-col pb-[max(env(safe-area-inset-bottom),0.75rem)] pt-[max(env(safe-area-inset-top),1.5rem)]">
    <div className="mb-4 flex min-h-12 items-center justify-between gap-4"><h2 className="text-[32px] font-black leading-none tracking-normal">Сплитик</h2><span className="grid h-14 w-14 place-items-center rounded-[18px] border-2 border-white/86 bg-white/8 text-white"><Bot className="h-7 w-7" strokeWidth={2.5} /></span></div>
    <div data-testid="splitik-chat-shell" className="flex min-h-0 flex-1 flex-col"><div data-testid="splitik-message-list" className="flex min-h-0 flex-1 flex-col justify-end gap-3 overflow-y-auto px-1 pb-3 pt-2" onScroll={(event) => { const element = event.currentTarget; setIsNearLatestMessage(element.scrollHeight - element.scrollTop - element.clientHeight < 96); }}>
      {messages.map((item) => <div key={item.id} className={cn("grid gap-2", item.from === "user" ? "justify-items-end" : "justify-items-start")}><div className={cn("max-w-[86%] rounded-2xl px-3 py-2 text-[15px] leading-6", item.from === "user" ? "ml-auto bg-white font-bold text-[#1f3d8f]" : "mr-auto bg-[#eef1f7] font-medium text-slate-900", item.delivery === "failed" && "border border-amber-300")}>{item.from === "splitik" ? <MarkdownMessage text={item.text} /> : item.text}</div>
        {item.from === "splitik" && item.drafts?.length ? <div className="grid w-full max-w-[92%] gap-2">{item.drafts.map((draftItem) => <SplitikDraftCard key={draftItem.id} draft={draftItem} onOpen={setActiveDraft} onConfirm={onConfirmDraft} onEdit={applyDraftPrompt} />)}</div> : null}
        {item.from === "splitik" && item.questions?.length ? <div className="grid w-full max-w-[92%] gap-1 rounded-2xl border border-[#d8dfeb] bg-white px-3 py-3 text-sm font-bold text-slate-700"><span className="text-[11px] font-black uppercase tracking-wide text-[#1f3d8f]">Нужно уточнить</span>{item.questions.map((question) => <button key={question.id} type="button" className="text-left leading-5" onClick={() => onDraft(question.text)}>{question.text}</button>)}</div> : null}
        {item.retryMessage ? <div className="flex flex-wrap gap-2 px-1"><Button type="button" variant="secondary" className="min-h-11 rounded-xl bg-white text-sm font-black text-[#1f3d8f] hover:bg-[#eef1f7]" onClick={() => { const retryUserMessage = [...messages].reverse().find((message) => message.from === "user" && message.text.startsWith(item.retryMessage!)); onSend(item.retryMessage, retryUserMessage?.id, retryUserMessage?.idempotencyKey); }}>Повторить отправку</Button><Button type="button" variant="ghost" className="min-h-11 rounded-xl px-2 text-sm font-black text-white underline hover:bg-white/10" onClick={() => onCreateEventManually(item.retryMessage!)}>Создать событие вручную</Button></div> : null}
      </div>)}<div ref={messageEndRef} data-testid="splitik-message-end" /></div>
      <form onSubmit={(event) => { event.preventDefault(); onSend(); }} data-testid="splitik-composer" className="mt-2 grid shrink-0 gap-2 rounded-2xl bg-white p-2 shadow-[0_14px_36px_rgba(15,23,42,0.18)]">{attachments.length ? <div className="flex flex-wrap gap-2 px-1 pt-1">{attachments.map((attachment) => <span key={attachment.id} className="rounded-full bg-[#eef1f7] px-3 py-1.5 text-xs font-black text-[#1f3d8f]">{attachment.filename}</span>)}</div> : null}<div className="flex gap-2"><Button asChild type="button" aria-label="Прикрепить фото чека" variant="ghost" className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#eef1f7] p-0 text-[#1f3d8f] hover:bg-[#dfe5f1]"><label>{isAttachmentUploading ? <span className="h-4 w-4 animate-spin rounded-full border-2 border-[#1f3d8f]/30 border-t-[#1f3d8f]" /> : <ImageIcon className="h-5 w-5" />}<input data-testid="splitik-attachment-input" type="file" accept="image/*" className="hidden" disabled={isAttachmentUploading || isSending} onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) onAttachReceipt(file); event.currentTarget.value = ""; }} /></label></Button><textarea ref={messageInputRef} aria-label="Сообщение Сплитику" data-testid="splitik-message-input" rows={1} className="min-h-12 max-h-[132px] flex-1 resize-none overflow-y-auto rounded-xl border border-slate-200 bg-white px-3 py-3 text-[16px] font-semibold leading-5 text-slate-950 outline-none focus-visible:ring-2 focus-visible:ring-[#1f3d8f]" placeholder="Напишите сообщение..." value={draft} onChange={(event) => updateDraft(event.target.value)} onFocus={() => scrollToLatestMessage(true)} /><Button type="submit" aria-label="Отправить Сплитику" disabled={isSending || isAttachmentUploading || (!draft.trim() && !attachments.length)} className="grid h-12 w-12 place-items-center rounded-xl bg-[#1f3d8f] p-0 text-white hover:bg-[#1f3d8f]/90 disabled:opacity-60">{isSending ? <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" /> : <Send className="h-5 w-5" />}</Button></div></form>
      <SplitikDraftSheet draft={activeDraft} onClose={() => setActiveDraft(null)} onEdit={(value) => { setActiveDraft(null); applyDraftPrompt(value); }} onConfirm={(draftId) => { setActiveDraft(null); onConfirmDraft(draftId); }} />
    </div></section></div>;
}

function MarkdownMessage({ text }: { text: string }) { return <div className="space-y-2">{parseMarkdownMessage(text).map((block, index) => block.type === "list" ? <ul key={index} className="ml-4 list-disc space-y-1">{block.items.map((item, itemIndex) => <li key={itemIndex}>{renderInlineMarkdown(item)}</li>)}</ul> : <p key={index}>{renderInlineMarkdown(block.text)}</p>)}</div>; }
function SplitikDraftCard({ draft, onOpen, onConfirm, onEdit }: { draft: SplitikDraft; onOpen: (draft: SplitikDraft) => void; onConfirm: (draftId: string) => void; onEdit: (value: string) => void; }) { const title = splitikDraftTitle(draft); const details = splitikDraftDetails(draft); const isCommitted = draft.status === "committed"; return <Card data-testid="splitik-draft-card" className="overflow-hidden rounded-2xl border-[#d8dfeb] bg-white shadow-sm"><CardHeader className="grid gap-2 p-3 pb-2"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#eef1f7] text-[#1f3d8f]">{draft.type === "create_receipt" ? <ReceiptText className="h-5 w-5" /> : <CalendarCheck className="h-5 w-5" />}</span><div className="min-w-0"><CardTitle className="truncate text-sm font-black text-slate-950">{title}</CardTitle><p className="text-xs font-bold text-slate-500">{splitikDraftKind(draft)}</p></div></div><Badge className={cn("rounded-full px-2.5 py-1 text-[10px] font-black", isCommitted ? "bg-emerald-100 text-emerald-700" : "bg-[#d2daec] text-[#1f3d8f]")}>{isCommitted ? "Подтвержден" : "Черновик"}</Badge></div></CardHeader><CardContent className="grid gap-3 p-3 pt-0"><div className="grid gap-1.5 rounded-xl bg-[#f5f7fb] p-3">{details.map(([label, value]) => <div key={label} className="flex items-start justify-between gap-3 text-xs"><span className="font-bold text-slate-500">{label}</span><span className="max-w-[62%] text-right font-black text-slate-900">{value}</span></div>)}</div>{draft.questions?.length ? <div className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">Нужно уточнить: {draft.questions.map((question) => question.text).join(" · ")}</div> : null}<div className="grid gap-2"><Button data-testid="splitik-draft-open" type="button" className="min-h-11 rounded-xl bg-[#1f3d8f] px-3 text-sm font-black text-white hover:bg-[#1f3d8f]/90" onClick={() => onOpen(draft)}><ExternalLink className="mr-1 h-4 w-4" />Открыть черновик</Button><div className="grid grid-cols-2 gap-2"><Button type="button" variant="ghost" className="h-10 rounded-xl bg-[#eef1f7] px-2 text-xs font-black text-[#1f3d8f]" onClick={() => onEdit(`Измени черновик ${draft.id}: `)}><PencilLine className="mr-1 h-4 w-4" />Изменить</Button><Button data-testid="splitik-draft-confirm" type="button" disabled={isCommitted} className="h-10 rounded-xl bg-[#111111] px-2 text-xs font-black text-white hover:bg-[#111111]/90 disabled:bg-slate-300" onClick={() => onConfirm(draft.id)}><Check className="mr-1 h-4 w-4" />OK</Button></div></div></CardContent></Card>; }
function SplitikDraftSheet({ draft, onClose, onEdit, onConfirm }: { draft: SplitikDraft | null; onClose: () => void; onEdit: (value: string) => void; onConfirm: (draftId: string) => void; }) { if (!draft) return null; const title = splitikDraftTitle(draft); const details = splitikDraftDetails(draft); const isCommitted = draft.status === "committed"; return <AnimatePresence><motion.div data-testid="splitik-draft-sheet" className="fixed inset-0 z-50 grid items-end bg-slate-950/40 px-3 pb-[calc(76px+env(safe-area-inset-bottom))] backdrop-blur-[2px]" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div className="mx-auto grid max-h-[74dvh] w-full max-w-[var(--content-max)] gap-4 overflow-y-auto rounded-[28px] bg-white p-4 text-slate-950 shadow-[0_24px_70px_rgba(15,23,42,0.34)]" initial={{ y: 28 }} animate={{ y: 0 }} exit={{ y: 28 }} transition={{ duration: 0.18 }}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-wide text-[#1f3d8f]">{splitikDraftKind(draft)}</p><h3 className="mt-1 break-words text-2xl font-black leading-tight">{title}</h3></div><Badge className={cn("shrink-0 rounded-full px-3 py-1 text-[10px] font-black", isCommitted ? "bg-emerald-100 text-emerald-700" : "bg-[#d2daec] text-[#1f3d8f]")}>{isCommitted ? "Подтвержден" : "Черновик"}</Badge></div><div className="grid gap-2 rounded-2xl bg-[#f5f7fb] p-3">{details.map(([label, value]) => <div key={label} className="grid grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)] gap-3 text-sm"><span className="font-bold text-slate-500">{label}</span><span className="break-words text-right font-black text-slate-900">{value}</span></div>)}</div>{draft.questions?.length ? <div className="rounded-2xl border border-amber-200 bg-amber-50 px-3 py-2 text-sm font-bold text-amber-800">Нужно уточнить: {draft.questions.map((question) => question.text).join(" · ")}</div> : null}<div className="grid grid-cols-2 gap-2"><Button type="button" variant="secondary" className="min-h-12 rounded-2xl bg-[#eef1f7] text-sm font-black text-slate-700 hover:bg-[#e2e7f2]" onClick={onClose}>Закрыть</Button><Button type="button" variant="ghost" className="min-h-12 rounded-2xl bg-[#eef1f7] text-sm font-black text-[#1f3d8f]" onClick={() => onEdit(`Измени черновик ${draft.id}: `)}>Изменить</Button></div><Button data-testid="splitik-draft-sheet-confirm" type="button" disabled={isCommitted} className="min-h-12 rounded-2xl bg-[#1f3d8f] text-sm font-black text-white hover:bg-[#1f3d8f]/90 disabled:bg-slate-300" onClick={() => onConfirm(draft.id)}>Подтвердить черновик</Button></motion.div></motion.div></AnimatePresence>; }
function splitikDraftKind(draft: SplitikDraft) { return draft.type === "create_event" ? "Черновик события" : draft.type === "create_receipt" ? "Черновик чека" : "Черновик"; }
function splitikDraftTitle(draft: SplitikDraft) { const payload = draft.payload; return draft.type === "create_event" ? stringValue(payload.name) || "Новое событие" : draft.type === "create_receipt" ? stringValue(payload.title) || "Новый чек" : "Черновик"; }
function splitikDraftDetails(draft: SplitikDraft): Array<[string, string]> { const payload = draft.payload; if (draft.type === "create_event") return [["Название", stringValue(payload.name) || "Без названия"], ["Статус", draft.status === "committed" ? "подтвержден" : "ожидает подтверждения"]]; if (draft.type === "create_receipt") { const items = Array.isArray(payload.items) ? payload.items : []; return [["Сумма", money(numberValue(payload.total_amount_kopecks))], ["Плательщик", shortId(stringValue(payload.payer_id))], ["Позиции", items.length ? `${items.length}` : "не указаны"]]; } return [["Статус", draft.status]]; }
function stringValue(value: unknown) { return typeof value === "string" ? value : ""; }
function numberValue(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? value : 0; }
function shortId(value: string) { return value ? `${value.slice(0, 8)}...` : "не указан"; }
function parseMarkdownMessage(text: string): Array<{ type: "paragraph"; text: string } | { type: "list"; items: string[] }> { const blocks: Array<{ type: "paragraph"; text: string } | { type: "list"; items: string[] }> = []; let paragraph: string[] = []; let listItems: string[] = []; const flushParagraph = () => { if (paragraph.length) { blocks.push({ type: "paragraph", text: paragraph.join(" ") }); paragraph = []; } }; const flushList = () => { if (listItems.length) { blocks.push({ type: "list", items: listItems }); listItems = []; } }; for (const rawLine of text.split(/\r?\n/)) { const line = rawLine.trim(); if (!line) { flushParagraph(); flushList(); } else if (line.startsWith("- ")) { flushParagraph(); listItems.push(line.slice(2).trim()); } else { flushList(); paragraph.push(line); } } flushParagraph(); flushList(); return blocks.length ? blocks : [{ type: "paragraph", text }]; }
function renderInlineMarkdown(text: string) { return text.split(/(\*\*[^*]+\*\*)/g).map((part, index) => part.startsWith("**") && part.endsWith("**") ? <strong key={index}>{part.slice(2, -2)}</strong> : part); }
